In [1]:
import requests
import pandas as pd

In [17]:
# Define parameters
api_key = "71166a96655234262760b0975365279ba3b63e04"
years = range(2013, 2024)
vars = "NAME,DP05_0001E,DP05_0003PE,DP05_0002PE,DP05_0017E,DP02_0065PE,DP02_0066PE,DP02_0061PE,DP05_0077PE,DP05_0078PE,DP05_0080PE,DP05_0071PE,DP03_0062E"

In [ ]:
all_data = []

for year in years:
    # URL for ACS 5-Year Data Profile
    url = f"https://api.census.gov/data/{year}/acs/acs5/profile?get={vars}&for=county:*&key={api_key}"
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        df = pd.DataFrame(data[1:], columns=data[0])
        df['year'] = year # Add year column for tracking
        all_data.append(df)

# Combine and save
final_df = pd.concat(all_data, ignore_index=True)
final_df.to_csv("combined_census_final.csv", index=False)

In [19]:
final_df.head()

,NAME,DP05_0001E,DP05_0003PE,DP05_0002PE,DP05_0017E,DP02_0065PE,DP02_0066PE,DP02_0061PE,DP05_0077PE,DP05_0078PE,DP05_0080PE,DP05_0071PE,DP03_0062E,state,county,year
0,"Escambia County, Florida",300795,50.5,49.5,37.4,8.3,87.9,28.5,0.1,3.6,3.5,95.1,43918,12,033,2013
1,"Hernando County, Florida",173119,52.1,47.9,48.0,4.9,86.5,38.4,0.2,1.5,1.4,89.4,41024,12,053,2013
2,"Hillsborough County, Florida",1257913,51.2,48.8,36.3,10.4,86.8,28.0,0.3,2.0,1.8,74.7,49596,12,057,2013
3,"Okaloosa County, Florida",185852,49.7,50.3,37.4,11.0,90.9,27.2,0.2,3.6,3.5,92.6,54684,12,091,2013
4,"Taylor County, Florida",22660,43.6,56.4,41.4,4.7,76.5,37.1,0.0,1.5,1.5,96.3,36356,12,123,2013

In [20]:
# update column names
final_df = final_df.rename(columns={
    "DP05_0001E":  "total_population",
    "DP05_0002PE": "pct_male",
    "DP05_0003PE": "pct_female",
    "DP05_0017E":  "median_age",
    "DP02_0065PE": "pct_bachelors_plus",
    "DP02_0066PE": "pct_graduate_degree",
    "DP02_0061PE": "pct_less_than_hs",
    "DP05_0077PE": "pct_white",
    "DP05_0078PE": "pct_black",
    "DP05_0080PE": "pct_asian",
    "DP05_0071PE": "pct_hispanic",
    "DP03_0062E":  "median_household_income"
})

print(final_df.columns.tolist())
final_df.head()

['NAME', 'total_population', 'pct_female', 'pct_male', 'median_age', 'pct_bachelors_plus', 'pct_graduate_degree', 'pct_less_than_hs', 'pct_white', 'pct_black', 'pct_asian', 'pct_hispanic', 'median_household_income', 'state', 'county', 'year']

,NAME,total_population,pct_female,pct_male,median_age,pct_bachelors_plus,pct_graduate_degree,pct_less_than_hs,pct_white,pct_black,pct_asian,pct_hispanic,median_household_income,state,county,year
0,"Escambia County, Florida",300795,50.5,49.5,37.4,8.3,87.9,28.5,0.1,3.6,3.5,95.1,43918,12,033,2013
1,"Hernando County, Florida",173119,52.1,47.9,48.0,4.9,86.5,38.4,0.2,1.5,1.4,89.4,41024,12,053,2013
2,"Hillsborough County, Florida",1257913,51.2,48.8,36.3,10.4,86.8,28.0,0.3,2.0,1.8,74.7,49596,12,057,2013
3,"Okaloosa County, Florida",185852,49.7,50.3,37.4,11.0,90.9,27.2,0.2,3.6,3.5,92.6,54684,12,091,2013
4,"Taylor County, Florida",22660,43.6,56.4,41.4,4.7,76.5,37.1,0.0,1.5,1.5,96.3,36356,12,123,2013

In [21]:
# add CountyFIPS column

final_df["CountyFIPS"] = (
    final_df["state"].astype(str).str.zfill(2) +
    final_df["county"].astype(str).str.zfill(3)
)

In [23]:
# export final dataset

final_df.to_csv("combined_census_final.csv", index=False)